provisionDataStore:
  cassandra: false
  elasticsearch: false

allInOne:
  enabled: true
  service:
    headless: false
  ingress:
    enabled: true
    hosts:
    - "jaeger.127.0.0.1"

storage:
  type: none
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
