resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

ingress:
  enabled: true
  className: null
  hosts:
  - host: kibana.127.0.0.1
    paths:
    - path: /
