image:
  repository: kong/kong-gateway
  tag: 3.3.1.0-ubuntu
  pullPolicy: IfNotPresent

migrations:
  preUpgrade: true
  postUpgrade: true

env:
  database: postgres
  admin_api_uri: "https://kong-admin.INGRESS_DOMAIN"
  admin_gui_url: "https://kong-manager.INGRESS_DOMAIN"
  pg_database: kong
  pg_user: kong
  pg_password: kong
  pg_host: kongcp-postgresql
  portal_gui_host: "kong-portal.INGRESS_DOMAIN"
  portal_auth: "basic-auth"
  portal_gui_protocol: "https"
  portal_api_url: "https://kong-portalapi.INGRESS_DOMAIN"
  vaults: "off"

  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  password:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password
        key: password

  portal_session_conf:
    valueFrom:
      secretKeyRef:
        name: kong-session-config
        key: portal_session_conf

secretVolumes:
- kong-cluster-cert

proxy:
  enabled: false

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: false
    servicePort: 8001
    containerPort: 8001
  tls:
    enabled: true
    servicePort: 8444
    containerPort: 8444
    parameters: []
  ingress:
    enabled: true
    hostname: kong-admin.INGRESS_DOMAIN

manager:
  enabled: true
  type: ClusterIP
  http:
    enabled: false
    servicePort: 8002
    containerPort: 8002
  tls:
    enabled: true
    containerPort: 8445
    servicePort: 8445
    parameters: []
  ingress:
    enabled: true
    hostname: kong-manager.INGRESS_DOMAIN

portal:
  enabled: true
  type: ClusterIP
  http:
    enabled: false
    servicePort: 8003
    containerPort: 8003
  tls:
    enabled: true
    containerPort: 8446
    servicePort: 8446
    parameters: []
  ingress:
    enabled: true
    hostname: kong-portal.INGRESS_DOMAIN

portalapi:
  enabled: true
  type: ClusterIP
  http:
    enabled: false
    servicePort: 8004
    containerPort: 8004
  tls:
    enabled: true
    containerPort: 8447
    servicePort: 8447
    parameters: []
  ingress:
    enabled: true
    hostname: kong-portalapi.INGRESS_DOMAIN

cluster:
  enabled: true
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005

clustertelemetry:
  enabled: true
  tls:
    enabled: true
    servicePort: 8006
    containerPort: 8006

enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  vitals:
    enabled: true
  portal:
    enabled: true
  rbac:
    enabled: true
    admin_gui_auth: basic-auth
    session_conf_secret: kong-session-config
  smtp:
    enabled: false

postgresql:
  enabled: true
  auth:
    username: kong
    password: kong

ingressController:
  enabled: false
  installCRDs: false
